//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hanamiSushiBar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id_product { get; set; }
        public string name { get; set; }
        public string details { get; set; }
        public Nullable<double> price { get; set; }
        public string img_url { get; set; }
        public string @ref { get; set; }
        public int id_category { get; set; }
    
        public virtual categories categories { get; set; }
    }
}
